import { Element } from '@/types/element';

export const elements: Element[] = [
  {
    atomicNumber: 1,
    symbol: 'H',
    name: '수소',
    englishName: 'Hydrogen',
    atomicWeight: '1.008',
    category: 'nonmetal',
    electronConfiguration: '1s¹',
    position: { row: 1, column: 1 },
  },
  {
    atomicNumber: 2,
    symbol: 'He',
    name: '헬륨',
    englishName: 'Helium',
    atomicWeight: '4.0026',
    category: 'noble gas',
    electronConfiguration: '1s²',
    position: { row: 1, column: 18 },
  },
  {
    atomicNumber: 3,
    symbol: 'Li',
    name: '리튬',
    englishName: 'Lithium',
    atomicWeight: '6.94',
    category: 'alkali metal',
    electronConfiguration: '[He] 2s¹',
    position: { row: 2, column: 1 },
    density: 0.534,
    meltingPoint: 453.69,
  },
  {
    atomicNumber: 4,
    symbol: 'Be',
    name: '베릴륨',
    englishName: 'Beryllium',
    atomicWeight: '9.0122',
    category: 'alkaline earth metal',
    electronConfiguration: '[He] 2s²',
    position: { row: 2, column: 2 },
    density: 1.85,
    meltingPoint: 1560,
  },
  {
    atomicNumber: 5,
    symbol: 'B',
    name: '붕소',
    englishName: 'Boron',
    atomicWeight: '10.81',
    category: 'metalloid',
    electronConfiguration: '[He] 2s² 2p¹',
    position: { row: 2, column: 13 },
    density: 2.34,
    meltingPoint: 2349,
  },
  {
    atomicNumber: 6,
    symbol: 'C',
    name: '탄소',
    englishName: 'Carbon',
    atomicWeight: '12.011',
    category: 'nonmetal',
    electronConfiguration: '[He] 2s² 2p²',
    position: { row: 2, column: 14 },
    density: 2.267,
    meltingPoint: 3800,
  },
  {
    atomicNumber: 7,
    symbol: 'N',
    name: '질소',
    englishName: 'Nitrogen',
    atomicWeight: '14.007',
    category: 'nonmetal',
    electronConfiguration: '[He] 2s² 2p³',
    position: { row: 2, column: 15 },
    density: 0.0012506,
    meltingPoint: 63.15,
  },
  {
    atomicNumber: 8,
    symbol: 'O',
    name: '산소',
    englishName: 'Oxygen',
    atomicWeight: '15.999',
    category: 'nonmetal',
    electronConfiguration: '[He] 2s² 2p⁴',
    position: { row: 2, column: 16 },
    density: 0.001429,
    meltingPoint: 54.36,
  },
  {
    atomicNumber: 9,
    symbol: 'F',
    name: '플루오린',
    englishName: 'Fluorine',
    atomicWeight: '18.998',
    category: 'nonmetal',
    electronConfiguration: '[He] 2s² 2p⁵',
    position: { row: 2, column: 17 },
    density: 0.001696,
    meltingPoint: 53.53,
  },
  {
    atomicNumber: 10,
    symbol: 'Ne',
    name: '네온',
    englishName: 'Neon',
    atomicWeight: '20.180',
    category: 'noble gas',
    electronConfiguration: '[He] 2s² 2p⁶',
    position: { row: 2, column: 18 },
    density: 0.0008999,
    meltingPoint: 24.56,
  },
  {
    atomicNumber: 11,
    symbol: 'Na',
    name: '나트륨',
    englishName: 'Sodium',
    atomicWeight: '22.990',
    category: 'alkali metal',
    electronConfiguration: '[Ne] 3s¹',
    position: { row: 3, column: 1 },
    density: 0.968,
    meltingPoint: 370.87,
  },
  {
    atomicNumber: 12,
    symbol: 'Mg',
    name: '마그네슘',
    englishName: 'Magnesium',
    atomicWeight: '24.305',
    category: 'alkaline earth metal',
    electronConfiguration: '[Ne] 3s²',
    position: { row: 3, column: 2 },
    density: 1.738,
    meltingPoint: 923,
  },
  {
    atomicNumber: 13,
    symbol: 'Al',
    name: '알루미늄',
    englishName: 'Aluminum',
    atomicWeight: '26.982',
    category: 'post-transition metal',
    electronConfiguration: '[Ne] 3s² 3p¹',
    position: { row: 3, column: 13 },
    density: 2.7,
    meltingPoint: 933.47,
  },
  {
    atomicNumber: 14,
    symbol: 'Si',
    name: '규소',
    englishName: 'Silicon',
    atomicWeight: '28.085',
    category: 'metalloid',
    electronConfiguration: '[Ne] 3s² 3p²',
    position: { row: 3, column: 14 },
    density: 2.3296,
    meltingPoint: 1687,
  },
  {
    atomicNumber: 15,
    symbol: 'P',
    name: '인',
    englishName: 'Phosphorus',
    atomicWeight: '30.974',
    category: 'nonmetal',
    electronConfiguration: '[Ne] 3s² 3p³',
    position: { row: 3, column: 15 },
    density: 1.82,
    meltingPoint: 317.3,
  },
  {
    atomicNumber: 16,
    symbol: 'S',
    name: '황',
    englishName: 'Sulfur',
    atomicWeight: '32.06',
    category: 'nonmetal',
    electronConfiguration: '[Ne] 3s² 3p⁴',
    position: { row: 3, column: 16 },
    density: 2.067,
    meltingPoint: 388.36,
  },
  {
    atomicNumber: 17,
    symbol: 'Cl',
    name: '염소',
    englishName: 'Chlorine',
    atomicWeight: '35.45',
    category: 'nonmetal',
    electronConfiguration: '[Ne] 3s² 3p⁵',
    position: { row: 3, column: 17 },
    density: 0.003214,
    meltingPoint: 171.6,
  },
  {
    atomicNumber: 18,
    symbol: 'Ar',
    name: '아르곤',
    englishName: 'Argon',
    atomicWeight: '39.948',
    category: 'noble gas',
    electronConfiguration: '[Ne] 3s² 3p⁶',
    position: { row: 3, column: 18 },
    density: 0.0017837,
    meltingPoint: 83.8,
  },
  {
    atomicNumber: 19,
    symbol: 'K',
    name: '칼륨',
    englishName: 'Potassium',
    atomicWeight: '39.098',
    category: 'alkali metal',
    electronConfiguration: '[Ar] 4s¹',
    position: { row: 4, column: 1 },
    density: 0.862,
    meltingPoint: 336.53,
  },
  {
    atomicNumber: 20,
    symbol: 'Ca',
    name: '칼슘',
    englishName: 'Calcium',
    atomicWeight: '40.078',
    category: 'alkaline earth metal',
    electronConfiguration: '[Ar] 4s²',
    position: { row: 4, column: 2 },
    density: 1.54,
    meltingPoint: 1115,
  },

  {
    atomicNumber: 21,
    symbol: 'Sc',
    name: '스칸듐',
    englishName: 'Scandium',
    atomicWeight: '44.956',
    category: 'transition metal',
    electronConfiguration: '[Ar] 3d¹ 4s²',
    position: { row: 4, column: 3 },
    density: 2.989,
    meltingPoint: 1814,
  },
  {
    atomicNumber: 22,
    symbol: 'Ti',
    name: '티타늄',
    englishName: 'Titanium',
    atomicWeight: '47.867',
    category: 'transition metal',
    electronConfiguration: '[Ar] 3d² 4s²',
    position: { row: 4, column: 4 },
    density: 4.54,
    meltingPoint: 1941,
  },
  {
    atomicNumber: 23,
    symbol: 'V',
    name: '바나듐',
    englishName: 'Vanadium',
    atomicWeight: '50.942',
    category: 'transition metal',
    electronConfiguration: '[Ar] 3d³ 4s²',
    position: { row: 4, column: 5 },
    density: 6.11,
    meltingPoint: 2183,
  },
  {
    atomicNumber: 24,
    symbol: 'Cr',
    name: '크롬',
    englishName: 'Chromium',
    atomicWeight: '51.996',
    category: 'transition metal',
    electronConfiguration: '[Ar] 3d⁵ 4s¹',
    position: { row: 4, column: 6 },
    density: 7.15,
    meltingPoint: 2180,
  },
  {
    atomicNumber: 25,
    symbol: 'Mn',
    name: '망간',
    englishName: 'Manganese',
    atomicWeight: '54.938',
    category: 'transition metal',
    electronConfiguration: '[Ar] 3d⁵ 4s²',
    position: { row: 4, column: 7 },
    density: 7.44,
    meltingPoint: 1519,
  },
  {
    atomicNumber: 26,
    symbol: 'Fe',
    name: '철',
    englishName: 'Iron',
    atomicWeight: '55.845',
    category: 'transition metal',
    electronConfiguration: '[Ar] 3d⁶ 4s²',
    position: { row: 4, column: 8 },
    density: 7.874,
    meltingPoint: 1811,
  },
  {
    atomicNumber: 27,
    symbol: 'Co',
    name: '코발트',
    englishName: 'Cobalt',
    atomicWeight: '58.933',
    category: 'transition metal',
    electronConfiguration: '[Ar] 3d⁷ 4s²',
    position: { row: 4, column: 9 },
    density: 8.86,
    meltingPoint: 1768,
  },
  {
    atomicNumber: 28,
    symbol: 'Ni',
    name: '니켈',
    englishName: 'Nickel',
    atomicWeight: '58.693',
    category: 'transition metal',
    electronConfiguration: '[Ar] 3d⁸ 4s²',
    position: { row: 4, column: 10 },
    density: 8.912,
    meltingPoint: 1728,
  },
  {
    atomicNumber: 29,
    symbol: 'Cu',
    name: '구리',
    englishName: 'Copper',
    atomicWeight: '63.546',
    category: 'transition metal',
    electronConfiguration: '[Ar] 3d¹⁰ 4s¹',
    position: { row: 4, column: 11 },
    density: 8.96,
    meltingPoint: 1357.77,
  },
  {
    atomicNumber: 30,
    symbol: 'Zn',
    name: '아연',
    englishName: 'Zinc',
    atomicWeight: '65.38',
    category: 'transition metal',
    electronConfiguration: '[Ar] 3d¹⁰ 4s²',
    position: { row: 4, column: 12 },
    density: 7.134,
    meltingPoint: 692.68,
  },

  {
    atomicNumber: 31,
    symbol: 'Ga',
    name: '갈륨',
    englishName: 'Gallium',
    atomicWeight: '69.723',
    category: 'post-transition metal',
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p¹',
    position: { row: 4, column: 13 },
    density: 5.907,
    meltingPoint: 302.9146,
  },
  {
    atomicNumber: 32,
    symbol: 'Ge',
    name: '저마늄',
    englishName: 'Germanium',
    atomicWeight: '72.630',
    category: 'metalloid',
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p²',
    position: { row: 4, column: 14 },
    density: 5.323,
    meltingPoint: 1211.4,
  },
  {
    atomicNumber: 33,
    symbol: 'As',
    name: '비소',
    englishName: 'Arsenic',
    atomicWeight: '74.922',
    category: 'metalloid',
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p³',
    position: { row: 4, column: 15 },
    density: 5.727,
    meltingPoint: 1090,
  },
  {
    atomicNumber: 34,
    symbol: 'Se',
    name: '셀레늄',
    englishName: 'Selenium',
    atomicWeight: '78.971',
    category: 'nonmetal',
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p⁴',
    position: { row: 4, column: 16 },
    density: 4.809,
    meltingPoint: 494,
  },
  {
    atomicNumber: 35,
    symbol: 'Br',
    name: '브로민',
    englishName: 'Bromine',
    atomicWeight: '79.904',
    category: 'nonmetal',
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p⁵',
    position: { row: 4, column: 17 },
    density: 3.1028,
    meltingPoint: 265.8,
  },
  {
    atomicNumber: 36,
    symbol: 'Kr',
    name: '크립톤',
    englishName: 'Krypton',
    atomicWeight: '83.798',
    category: 'noble gas',
    electronConfiguration: '[Ar] 3d¹⁰ 4s² 4p⁶',
    position: { row: 4, column: 18 },
    density: 0.003733,
    meltingPoint: 115.79,
  },

  {
    atomicNumber: 37,
    symbol: 'Rb',
    name: '루비듐',
    englishName: 'Rubidium',
    atomicWeight: '85.468',
    category: 'alkali metal',
    electronConfiguration: '[Kr] 5s¹',
    position: { row: 5, column: 1 },
    density: 1.532,
    meltingPoint: 312.46,
  },
  {
    atomicNumber: 38,
    symbol: 'Sr',
    name: '스트론튬',
    englishName: 'Strontium',
    atomicWeight: '87.62',
    category: 'alkaline earth metal',
    electronConfiguration: '[Kr] 5s²',
    position: { row: 5, column: 2 },
    density: 2.64,
    meltingPoint: 1050,
  },
  {
    atomicNumber: 39,
    symbol: 'Y',
    name: '이트륨',
    englishName: 'Yttrium',
    atomicWeight: '88.906',
    category: 'transition metal',
    electronConfiguration: '[Kr] 4d¹ 5s²',
    position: { row: 5, column: 3 },
    density: 4.469,
    meltingPoint: 1799,
  },
  {
    atomicNumber: 40,
    symbol: 'Zr',
    name: '지르코늄',
    englishName: 'Zirconium',
    atomicWeight: '91.224',
    category: 'transition metal',
    electronConfiguration: '[Kr] 4d² 5s²',
    position: { row: 5, column: 4 },
    density: 6.506,
    meltingPoint: 2128,
  },
  {
    atomicNumber: 41,
    symbol: 'Nb',
    name: '니오븀',
    englishName: 'Niobium',
    atomicWeight: '92.906',
    category: 'transition metal',
    electronConfiguration: '[Kr] 4d⁴ 5s¹',
    position: { row: 5, column: 5 },
    density: 8.57,
    meltingPoint: 2750,
  },
  {
    atomicNumber: 42,
    symbol: 'Mo',
    name: '몰리브데넘',
    englishName: 'Molybdenum',
    atomicWeight: '95.95',
    category: 'transition metal',
    electronConfiguration: '[Kr] 4d⁵ 5s¹',
    position: { row: 5, column: 6 },
    density: 10.22,
    meltingPoint: 2896,
  },
  {
    atomicNumber: 43,
    symbol: 'Tc',
    name: '테크네튬',
    englishName: 'Technetium',
    atomicWeight: '98',
    category: 'transition metal',
    electronConfiguration: '[Kr] 4d⁵ 5s²',
    position: { row: 5, column: 7 },
    density: 11.5,
    meltingPoint: 2430,
  },
  {
    atomicNumber: 44,
    symbol: 'Ru',
    name: '루테늄',
    englishName: 'Ruthenium',
    atomicWeight: '101.07',
    category: 'transition metal',
    electronConfiguration: '[Kr] 4d⁷ 5s¹',
    position: { row: 5, column: 8 },
    density: 12.37,
    meltingPoint: 2607,
  },
  {
    atomicNumber: 45,
    symbol: 'Rh',
    name: '로듐',
    englishName: 'Rhodium',
    atomicWeight: '102.91',
    category: 'transition metal',
    electronConfiguration: '[Kr] 4d⁸ 5s¹',
    position: { row: 5, column: 9 },
    density: 12.41,
    meltingPoint: 2237,
  },
  {
    atomicNumber: 46,
    symbol: 'Pd',
    name: '팔라듐',
    englishName: 'Palladium',
    atomicWeight: '106.42',
    category: 'transition metal',
    electronConfiguration: '[Kr] 4d¹⁰',
    position: { row: 5, column: 10 },
    density: 12.02,
    meltingPoint: 1828.05,
  },
  {
    atomicNumber: 47,
    symbol: 'Ag',
    name: '은',
    englishName: 'Silver',
    atomicWeight: '107.87',
    category: 'transition metal',
    electronConfiguration: '[Kr] 4d¹⁰ 5s¹',
    position: { row: 5, column: 11 },
    density: 10.49,
    meltingPoint: 1234.93,
  },
  {
    atomicNumber: 48,
    symbol: 'Cd',
    name: '카드뮴',
    englishName: 'Cadmium',
    atomicWeight: '112.41',
    category: 'transition metal',
    electronConfiguration: '[Kr] 4d¹⁰ 5s²',
    position: { row: 5, column: 12 },
    density: 8.69,
    meltingPoint: 594.22,
  },
  {
    atomicNumber: 49,
    symbol: 'In',
    name: '인듐',
    englishName: 'Indium',
    atomicWeight: '114.82',
    category: 'post-transition metal',
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p¹',
    position: { row: 5, column: 13 },
    density: 7.31,
    meltingPoint: 429.75,
  },
  {
    atomicNumber: 50,
    symbol: 'Sn',
    name: '주석',
    englishName: 'Tin',
    atomicWeight: '118.71',
    category: 'post-transition metal',
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p²',
    position: { row: 5, column: 14 },
    density: 7.287,
    meltingPoint: 505.08,
  },
  {
    atomicNumber: 51,
    symbol: 'Sb',
    name: '안티모니',
    englishName: 'Antimony',
    atomicWeight: '121.76',
    category: 'metalloid',
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p³',
    position: { row: 5, column: 15 },
    density: 6.685,
    meltingPoint: 903.78,
  },
  {
    atomicNumber: 52,
    symbol: 'Te',
    name: '텔루륨',
    englishName: 'Tellurium',
    atomicWeight: '127.60',
    category: 'metalloid',
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p⁴',
    position: { row: 5, column: 16 },
    density: 6.232,
    meltingPoint: 722.66,
  },
  {
    atomicNumber: 53,
    symbol: 'I',
    name: '아이오딘',
    englishName: 'Iodine',
    atomicWeight: '126.90',
    category: 'nonmetal',
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p⁵',
    position: { row: 5, column: 17 },
    density: 4.93,
    meltingPoint: 386.85,
  },
  {
    atomicNumber: 54,
    symbol: 'Xe',
    name: '제논',
    englishName: 'Xenon',
    atomicWeight: '131.29',
    category: 'noble gas',
    electronConfiguration: '[Kr] 4d¹⁰ 5s² 5p⁶',
    position: { row: 5, column: 18 },
    density: 0.005887,
    meltingPoint: 161.4,
  },

  {
    atomicNumber: 55,
    symbol: 'Cs',
    name: '세슘',
    englishName: 'Cesium',
    atomicWeight: '132.91',
    category: 'alkali metal',
    electronConfiguration: '[Xe] 6s¹',
    position: { row: 6, column: 1 },
    density: 1.873,
    meltingPoint: 301.59,
  },
  {
    atomicNumber: 56,
    symbol: 'Ba',
    name: '바륨',
    englishName: 'Barium',
    atomicWeight: '137.33',
    category: 'alkaline earth metal',
    electronConfiguration: '[Xe] 6s²',
    position: { row: 6, column: 2 },
    density: 3.594,
    meltingPoint: 1000,
  },
  {
    atomicNumber: 57,
    symbol: 'La',
    name: '란타넘',
    englishName: 'Lanthanum',
    atomicWeight: '138.91',
    category: 'lanthanide',
    electronConfiguration: '[Xe] 5d¹ 6s²',
    position: { row: 6, column: 3 },
    density: 6.145,
    meltingPoint: 1193,
  },
  {
    atomicNumber: 58,
    symbol: 'Ce',
    name: '세륨',
    englishName: 'Cerium',
    atomicWeight: '140.12',
    category: 'lanthanide',
    electronConfiguration: '[Xe] 4f¹ 5d¹ 6s²',
    position: { row: 8, column: 4 },
    density: 6.77,
    meltingPoint: 1068,
  },
  {
    atomicNumber: 59,
    symbol: 'Pr',
    name: '프라세오디뮴',
    englishName: 'Praseodymium',
    atomicWeight: '140.91',
    category: 'lanthanide',
    electronConfiguration: '[Xe] 4f³ 6s²',
    position: { row: 8, column: 5 },
    density: 6.773,
    meltingPoint: 1208,
  },
  {
    atomicNumber: 60,
    symbol: 'Nd',
    name: '네오디뮴',
    englishName: 'Neodymium',
    atomicWeight: '144.24',
    category: 'lanthanide',
    electronConfiguration: '[Xe] 4f⁴ 6s²',
    position: { row: 8, column: 6 },
    density: 7.007,
    meltingPoint: 1297,
  },
  {
    atomicNumber: 61,
    symbol: 'Pm',
    name: '프로메튬',
    englishName: 'Promethium',
    atomicWeight: '145',
    category: 'lanthanide',
    electronConfiguration: '[Xe] 4f⁵ 6s²',
    position: { row: 8, column: 7 },
    density: 7.26,
    meltingPoint: 1315,
  },
  {
    atomicNumber: 62,
    symbol: 'Sm',
    name: '사마륨',
    englishName: 'Samarium',
    atomicWeight: '150.36',
    category: 'lanthanide',
    electronConfiguration: '[Xe] 4f⁶ 6s²',
    position: { row: 8, column: 8 },
    density: 7.52,
    meltingPoint: 1345,
  },
  {
    atomicNumber: 63,
    symbol: 'Eu',
    name: '유로퓸',
    englishName: 'Europium',
    atomicWeight: '151.96',
    category: 'lanthanide',
    electronConfiguration: '[Xe] 4f⁷ 6s²',
    position: { row: 8, column: 9 },
    density: 5.243,
    meltingPoint: 1099,
  },
  {
    atomicNumber: 64,
    symbol: 'Gd',
    name: '가돌리늄',
    englishName: 'Gadolinium',
    atomicWeight: '157.25',
    category: 'lanthanide',
    electronConfiguration: '[Xe] 4f⁷ 5d¹ 6s²',
    position: { row: 8, column: 10 },
    density: 7.895,
    meltingPoint: 1585,
  },
  {
    atomicNumber: 65,
    symbol: 'Tb',
    name: '터븀',
    englishName: 'Terbium',
    atomicWeight: '158.93',
    category: 'lanthanide',
    electronConfiguration: '[Xe] 4f⁹ 6s²',
    position: { row: 8, column: 11 },
    density: 8.229,
    meltingPoint: 1629,
  },
  {
    atomicNumber: 66,
    symbol: 'Dy',
    name: '디스프로슘',
    englishName: 'Dysprosium',
    atomicWeight: '162.50',
    category: 'lanthanide',
    electronConfiguration: '[Xe] 4f¹⁰ 6s²',
    position: { row: 8, column: 12 },
    density: 8.55,
    meltingPoint: 1680,
  },
  {
    atomicNumber: 67,
    symbol: 'Ho',
    name: '홀뮴',
    englishName: 'Holmium',
    atomicWeight: '164.93',
    category: 'lanthanide',
    electronConfiguration: '[Xe] 4f¹¹ 6s²',
    position: { row: 8, column: 13 },
    density: 8.795,
    meltingPoint: 1734,
  },
  {
    atomicNumber: 68,
    symbol: 'Er',
    name: '에르븀',
    englishName: 'Erbium',
    atomicWeight: '167.26',
    category: 'lanthanide',
    electronConfiguration: '[Xe] 4f¹² 6s²',
    position: { row: 8, column: 14 },
    density: 9.066,
    meltingPoint: 1802,
  },
  {
    atomicNumber: 69,
    symbol: 'Tm',
    name: '툴륨',
    englishName: 'Thulium',
    atomicWeight: '168.93',
    category: 'lanthanide',
    electronConfiguration: '[Xe] 4f¹³ 6s²',
    position: { row: 8, column: 15 },
    density: 9.321,
    meltingPoint: 1818,
  },
  {
    atomicNumber: 70,
    symbol: 'Yb',
    name: '이터븀',
    englishName: 'Ytterbium',
    atomicWeight: '173.05',
    category: 'lanthanide',
    electronConfiguration: '[Xe] 4f¹⁴ 6s²',
    position: { row: 8, column: 16 },
    density: 6.965,
    meltingPoint: 1097,
  },
  {
    atomicNumber: 71,
    symbol: 'Lu',
    name: '루테튬',
    englishName: 'Lutetium',
    atomicWeight: '174.97',
    category: 'lanthanide',
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹ 6s²',
    position: { row: 8, column: 17 },
    density: 9.84,
    meltingPoint: 1925,
  },
  {
    atomicNumber: 72,
    symbol: 'Hf',
    name: '하프늄',
    englishName: 'Hafnium',
    atomicWeight: '178.49',
    category: 'transition metal',
    electronConfiguration: '[Xe] 4f¹⁴ 5d² 6s²',
    position: { row: 6, column: 4 },
    density: 13.31,
    meltingPoint: 2506,
  },
  {
    atomicNumber: 73,
    symbol: 'Ta',
    name: '탄탈럼',
    englishName: 'Tantalum',
    atomicWeight: '180.95',
    category: 'transition metal',
    electronConfiguration: '[Xe] 4f¹⁴ 5d³ 6s²',
    position: { row: 6, column: 5 },
    density: 16.654,
    meltingPoint: 3290,
  },
  {
    atomicNumber: 74,
    symbol: 'W',
    name: '텅스텐',
    englishName: 'Tungsten',
    atomicWeight: '183.84',
    category: 'transition metal',
    electronConfiguration: '[Xe] 4f¹⁴ 5d⁴ 6s²',
    position: { row: 6, column: 6 },
    density: 19.25,
    meltingPoint: 3695,
  },
  {
    atomicNumber: 75,
    symbol: 'Re',
    name: '레늄',
    englishName: 'Rhenium',
    atomicWeight: '186.21',
    category: 'transition metal',
    electronConfiguration: '[Xe] 4f¹⁴ 5d⁵ 6s²',
    position: { row: 6, column: 7 },
    density: 21.02,
    meltingPoint: 3459,
  },
  {
    atomicNumber: 76,
    symbol: 'Os',
    name: '오스뮴',
    englishName: 'Osmium',
    atomicWeight: '190.23',
    category: 'transition metal',
    electronConfiguration: '[Xe] 4f¹⁴ 5d⁶ 6s²',
    position: { row: 6, column: 8 },
    density: 22.59,
    meltingPoint: 3306,
  },
  {
    atomicNumber: 77,
    symbol: 'Ir',
    name: '이리듐',
    englishName: 'Iridium',
    atomicWeight: '192.22',
    category: 'transition metal',
    electronConfiguration: '[Xe] 4f¹⁴ 5d⁷ 6s²',
    position: { row: 6, column: 9 },
    density: 22.56,
    meltingPoint: 2719,
  },
  {
    atomicNumber: 78,
    symbol: 'Pt',
    name: '백금',
    englishName: 'Platinum',
    atomicWeight: '195.08',
    category: 'transition metal',
    electronConfiguration: '[Xe] 4f¹⁴ 5d⁹ 6s¹',
    position: { row: 6, column: 10 },
    density: 21.45,
    meltingPoint: 2041.4,
  },
  {
    atomicNumber: 79,
    symbol: 'Au',
    name: '금',
    englishName: 'Gold',
    atomicWeight: '196.97',
    category: 'transition metal',
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s¹',
    position: { row: 6, column: 11 },
    density: 19.3,
    meltingPoint: 1337.33,
  },
  {
    atomicNumber: 80,
    symbol: 'Hg',
    name: '수은',
    englishName: 'Mercury',
    atomicWeight: '200.59',
    category: 'transition metal',
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s²',
    position: { row: 6, column: 12 },
    density: 13.546,
    meltingPoint: 234.32,
  },
  {
    atomicNumber: 81,
    symbol: 'Tl',
    name: '탈륨',
    englishName: 'Thallium',
    atomicWeight: '204.38',
    category: 'post-transition metal',
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹',
    position: { row: 6, column: 13 },
    density: 11.85,
    meltingPoint: 577,
  },
  {
    atomicNumber: 82,
    symbol: 'Pb',
    name: '납',
    englishName: 'Lead',
    atomicWeight: '207.2',
    category: 'post-transition metal',
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²',
    position: { row: 6, column: 14 },
    density: 11.34,
    meltingPoint: 600.61,
  },
  {
    atomicNumber: 83,
    symbol: 'Bi',
    name: '비스무트',
    englishName: 'Bismuth',
    atomicWeight: '208.98',
    category: 'post-transition metal',
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³',
    position: { row: 6, column: 15 },
    density: 9.78,
    meltingPoint: 544.7,
  },
  {
    atomicNumber: 84,
    symbol: 'Po',
    name: '폴로늄',
    englishName: 'Polonium',
    atomicWeight: '209',
    category: 'post-transition metal',
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴',
    position: { row: 6, column: 16 },
    density: 9.196,
    meltingPoint: 527,
  },
  {
    atomicNumber: 85,
    symbol: 'At',
    name: '아스타틴',
    englishName: 'Astatine',
    atomicWeight: '210',
    category: 'metalloid',
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵',
    position: { row: 6, column: 17 },
    density: 7,
    meltingPoint: 575,
  },
  {
    atomicNumber: 86,
    symbol: 'Rn',
    name: '라돈',
    englishName: 'Radon',
    atomicWeight: '222',
    category: 'noble gas',
    electronConfiguration: '[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶',
    position: { row: 6, column: 18 },
    density: 0.00973,
    meltingPoint: 202,
  },

  {
    atomicNumber: 87,
    symbol: 'Fr',
    name: '프랑슘',
    englishName: 'Francium',
    atomicWeight: '223',
    category: 'alkali metal',
    electronConfiguration: '[Rn] 7s¹',
    position: { row: 7, column: 1 },
    density: 1.87,
    meltingPoint: 300,
  },
  {
    atomicNumber: 88,
    symbol: 'Ra',
    name: '라듐',
    englishName: 'Radium',
    atomicWeight: '226',
    category: 'alkaline earth metal',
    electronConfiguration: '[Rn] 7s²',
    position: { row: 7, column: 2 },
    density: 5.5,
    meltingPoint: 973,
  },
  {
    atomicNumber: 89,
    symbol: 'Ac',
    name: '악티늄',
    englishName: 'Actinium',
    atomicWeight: '227',
    category: 'actinide',
    electronConfiguration: '[Rn] 6d¹ 7s²',
    position: { row: 7, column: 3 },
    density: 10.07,
    meltingPoint: 1323,
  },
  {
    atomicNumber: 90,
    symbol: 'Th',
    name: '토륨',
    englishName: 'Thorium',
    atomicWeight: '232.04',
    category: 'actinide',
    electronConfiguration: '[Rn] 6d² 7s²',
    position: { row: 9, column: 4 },
    density: 11.72,
    meltingPoint: 2115,
  },
  {
    atomicNumber: 91,
    symbol: 'Pa',
    name: '프로트악티늄',
    englishName: 'Protactinium',
    atomicWeight: '231.04',
    category: 'actinide',
    electronConfiguration: '[Rn] 5f² 6d¹ 7s²',
    position: { row: 9, column: 5 },
    density: 15.37,
    meltingPoint: 1841,
  },
  {
    atomicNumber: 92,
    symbol: 'U',
    name: '우라늄',
    englishName: 'Uranium',
    atomicWeight: '238.03',
    category: 'actinide',
    electronConfiguration: '[Rn] 5f³ 6d¹ 7s²',
    position: { row: 9, column: 6 },
    density: 19.1,
    meltingPoint: 1405.3,
  },
  {
    atomicNumber: 93,
    symbol: 'Np',
    name: '넵투늄',
    englishName: 'Neptunium',
    atomicWeight: '237',
    category: 'actinide',
    electronConfiguration: '[Rn] 5f⁴ 6d¹ 7s²',
    position: { row: 9, column: 7 },
    density: 20.45,
    meltingPoint: 917,
  },
  {
    atomicNumber: 94,
    symbol: 'Pu',
    name: '플루토늄',
    englishName: 'Plutonium',
    atomicWeight: '244',
    category: 'actinide',
    electronConfiguration: '[Rn] 5f⁶ 7s²',
    position: { row: 9, column: 8 },
    density: 19.84,
    meltingPoint: 912.5,
  },
  {
    atomicNumber: 95,
    symbol: 'Am',
    name: '아메리슘',
    englishName: 'Americium',
    atomicWeight: '243',
    category: 'actinide',
    electronConfiguration: '[Rn] 5f⁷ 7s²',
    position: { row: 9, column: 9 },
    density: 13.69,
    meltingPoint: 1449,
  },
  {
    atomicNumber: 96,
    symbol: 'Cm',
    name: '퀴륨',
    englishName: 'Curium',
    atomicWeight: '247',
    category: 'actinide',
    electronConfiguration: '[Rn] 5f⁷ 6d¹ 7s²',
    position: { row: 9, column: 10 },
    density: 13.51,
    meltingPoint: 1613,
  },
  {
    atomicNumber: 97,
    symbol: 'Bk',
    name: '버클륨',
    englishName: 'Berkelium',
    atomicWeight: '247',
    category: 'actinide',
    electronConfiguration: '[Rn] 5f⁹ 7s²',
    position: { row: 9, column: 11 },
    density: 14.79,
    meltingPoint: 1259,
  },
  {
    atomicNumber: 98,
    symbol: 'Cf',
    name: '캘리포늄',
    englishName: 'Californium',
    atomicWeight: '251',
    category: 'actinide',
    electronConfiguration: '[Rn] 5f¹⁰ 7s²',
    position: { row: 9, column: 12 },
    density: 15.1,
    meltingPoint: 1173,
  },
  {
    atomicNumber: 99,
    symbol: 'Es',
    name: '아인슈타이늄',
    englishName: 'Einsteinium',
    atomicWeight: '252',
    category: 'actinide',
    electronConfiguration: '[Rn] 5f¹¹ 7s²',
    position: { row: 9, column: 13 },
    density: 8.84,
    meltingPoint: 1133,
  },
  {
    atomicNumber: 100,
    symbol: 'Fm',
    name: '페르뮴',
    englishName: 'Fermium',
    atomicWeight: '257',
    category: 'actinide',
    electronConfiguration: '[Rn] 5f¹² 7s²',
    position: { row: 9, column: 14 },
    density: 9.7,
    meltingPoint: 1800,
  },
  {
    atomicNumber: 101,
    symbol: 'Md',
    name: '멘델레븀',
    englishName: 'Mendelevium',
    atomicWeight: '258',
    category: 'actinide',
    electronConfiguration: '[Rn] 5f¹³ 7s²',
    position: { row: 9, column: 15 },
    density: 10.3,
    meltingPoint: 1100,
  },
  {
    atomicNumber: 102,
    symbol: 'No',
    name: '노벨륨',
    englishName: 'Nobelium',
    atomicWeight: '259',
    category: 'actinide',
    electronConfiguration: '[Rn] 5f¹⁴ 7s²',
    position: { row: 9, column: 16 },
    density: 9.9,
    meltingPoint: 1100,
  },
  {
    atomicNumber: 103,
    symbol: 'Lr',
    name: '로렌슘',
    englishName: 'Lawrencium',
    atomicWeight: '266',
    category: 'actinide',
    electronConfiguration: '[Rn] 5f¹⁴ 7s² 7p¹',
    position: { row: 9, column: 17 },
    density: 15.6,
    meltingPoint: 1900,
  },
];
